
import React, { useState } from 'react';
import Modal from '../components/Modal/Modal';
import { useNavigate } from 'react-router-dom';

const frameworks = [
  { key: 'playwright', icon: '🎭', name: 'Playwright', lang: 'TS / JS / Python' },
  { key: 'selenium', icon: '🕹', name: 'Selenium', lang: 'Java / Python / C#' },
  { key: 'appium', icon: '📱', name: 'Appium', lang: 'Mobile · iOS / Android' },
];
const languages = ['TypeScript', 'JavaScript', 'Python'];
const runners = ['Playwright Test', 'Jest', 'Vitest'];
const testCases = ['TC-001', 'TC-002', 'TC-003', 'TC-004', 'TC-005', 'All (312)'];
const tabs = ['checkout.spec.ts', 'helpers.ts', 'fixtures.ts'];

const ScriptGeneratorPage: React.FC = () => {
  const navigate = useNavigate();
  const [selectedFW, setSelectedFW] = useState('playwright');
  const [language, setLanguage] = useState('TypeScript');
  const [runner, setRunner] = useState('Playwright Test');
  const [selectedCases, setSelectedCases] = useState(['TC-001', 'TC-002', 'TC-003']);
  const [activeTab, setActiveTab] = useState('checkout.spec.ts');
  const [script] = useState(`# Generated by CrawlIQ · Apr 25 2026 · Playwright/TypeScript\nimport { test, expect } from '@playwright/test';\n\ntest.describe('Checkout Flow', () => {\n  test('TC-001: Validates empty fields', async ({ page }) => {\n    await page.goto('/checkout');\n    await page.click('[data-testid="place-order-btn"]');\n    await expect(page.locator('.validation-error')).toBeVisible();\n    await expect(page.locator('.validation-error')).toHaveCount(4);\n  });\n\n  test('TC-002: Complete checkout with valid card', async ({ page }) => {\n    await page.goto('/checkout');\n    await page.fill('[name="firstName"]', 'John');\n    await page.fill('[name="cardNumber"]', '4111111111111111');\n    await page.click('[data-testid="place-order-btn"]');\n    await expect(page).toHaveURL('/order-confirmation');\n  });\n});`);
  const [modalOpen, setModalOpen] = useState(false);
  const [pendingGenerate, setPendingGenerate] = useState(false);

  const handleFWSelect = (fw: string) => setSelectedFW(fw);
  const handleLangChange = (e: React.ChangeEvent<HTMLSelectElement>) => setLanguage(e.target.value);
  const handleRunnerChange = (e: React.ChangeEvent<HTMLSelectElement>) => setRunner(e.target.value);
  const handleCaseToggle = (tc: string) => {
    if (tc === 'All (312)') {
      setSelectedCases(testCases.slice(0, 5));
    } else {
      setSelectedCases(selectedCases.includes(tc) ? selectedCases.filter(c => c !== tc) : [...selectedCases, tc]);
    }
  };
  const handleTab = (tab: string) => setActiveTab(tab);
  const handleCopy = () => navigator.clipboard.writeText(script);
  const handleDownload = () => {
    const blob = new Blob([script], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = activeTab;
    a.click();
  };

  return (
    <>
      <div className="content">
        <div className="section-header" style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <div className="section-title">Script Generator</div>
          <div className="section-line" />
          <div className="topbar-right" style={{ display: 'flex', gap: 8, marginLeft: 'auto' }}>
            <button className="btn btn-ghost" onClick={() => navigate('/test-cases')}>← Test Cases</button>
          </div>
        </div>
        <div className="two-col">
          <div>
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header">
                <span style={{ color: 'var(--accent)' }}>⚙️</span>
                <span className="card-title">Framework Selection</span>
              </div>
              <div className="card-body">
                <div className="framework-grid">
                  {frameworks.map(fw => (
                    <div
                      key={fw.key}
                      className={`fw-card${selectedFW === fw.key ? ' selected' : ''}`}
                      onClick={() => handleFWSelect(fw.key)}
                      style={{ userSelect: 'none' }}
                    >
                      <div className="fw-icon">{fw.icon}</div>
                      <div className="fw-name">{fw.name}</div>
                      <div className="fw-lang">{fw.lang}</div>
                    </div>
                  ))}
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 14 }}>
                  <div className="input-group" style={{ marginBottom: 0 }}>
                    <div className="input-label">Language</div>
                    <select value={language} onChange={handleLangChange}>
                      {languages.map(l => <option key={l}>{l}</option>)}
                    </select>
                  </div>
                  <div className="input-group" style={{ marginBottom: 0 }}>
                    <div className="input-label">Test Runner</div>
                    <select value={runner} onChange={handleRunnerChange}>
                      {runners.map(r => <option key={r}>{r}</option>)}
                    </select>
                  </div>
                </div>
                <div style={{ marginBottom: 14 }}>
                  <div className="input-label" style={{ marginBottom: 8 }}>Test Cases to Include</div>
                  <div className="chip-toggle">
                    {testCases.map(tc => (
                      <div
                        key={tc}
                        className={`chip-opt${selectedCases.includes(tc) ? ' sel' : ''}`}
                        onClick={() => handleCaseToggle(tc)}
                        style={{ userSelect: 'none' }}
                      >
                        {tc}
                      </div>
                    ))}
                  </div>
                </div>
                <button
                  className="btn btn-ghost"
                  style={{ width: '100%', justifyContent: 'center', padding: 11 }}
                  onClick={() => setModalOpen(true)}
                >
                  ⚡ Generate Scripts
                </button>
              </div>
            </div>
          </div>
          <div>
            <div className="card">
              <div className="card-header">
                <span style={{ color: 'var(--accent2)' }}>📝</span>
                <span className="card-title">Script Preview</span>
                <div style={{ marginLeft: 'auto', display: 'flex', gap: 6 }}>
                  <button className="btn btn-ghost" style={{ fontSize: 12, padding: '5px 10px' }} onClick={handleCopy}>Copy</button>
                  <button className="btn btn-primary" style={{ fontSize: 12, padding: '5px 10px' }} onClick={handleDownload}>⬇ Download</button>
                </div>
              </div>
              <div className="card-body">
                <div className="tabs" style={{ marginBottom: 14 }}>
                  {tabs.map(tab => (
                    <div
                      key={tab}
                      className={`tab${activeTab === tab ? ' active' : ''}`}
                      onClick={() => handleTab(tab)}
                      style={{ userSelect: 'none' }}
                    >
                      {tab}
                    </div>
                  ))}
                </div>
                <div className="code-preview">
                  {script.split('\n').map((line, i) => <div key={i}>{line}</div>)}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title="⚡ Confirm Script Generation"
        actions={
          <>
            <button className="btn btn-ghost" onClick={() => setModalOpen(false)}>Cancel</button>
            <button
              className="btn btn-primary"
              onClick={() => {
                setModalOpen(false);
                setPendingGenerate(true);
                setTimeout(() => setPendingGenerate(false), 1200);
                // Place actual script generation logic here if needed
              }}
            >
              Confirm & Generate
            </button>
          </>
        }
      >
        {`You're about to generate scripts for the selected test cases using the ${selectedFW.charAt(0).toUpperCase() + selectedFW.slice(1)} framework in ${language}.`}
        <br /><br />
        {/* Token details, similar to old Start Crawl modal */}
        {(() => {
          // Demo values for token usage
          const estUsage = 12400;
          const quota = 38000;
          const percent = Math.round((estUsage / quota) * 100);
          return (
            <>
              <div className="token-widget" style={{marginTop: 18, marginBottom: 0}}>
                <div className="token-row">
                  <div>
                    <div className="token-label">Est. Usage</div>
                    <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 700, fontSize: 16 }}>12,400</div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div className="token-label">Remaining after</div>
                    <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 700, fontSize: 16, color: 'var(--accent)' }}>{quota - estUsage}</div>
                  </div>
                </div>
                <div className="token-bar"><div className="token-fill ok" style={{ width: percent + '%' }}></div></div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 6, fontFamily: 'DM Mono, monospace' }}>{percent}% of monthly quota</div>
              </div>
              <div className="file-info-row">
                <span>📄</span>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 13, fontWeight: 500 }}>swagger-openapi-v3.pdf</div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'DM Mono, monospace' }}>2.4 MB · uploaded</div>
                  <div className="progress-bar" style={{ marginTop: 6 }}><div className="progress-fill running" style={{ width: '100%' }}></div></div>
                </div>
                <span style={{ color: 'var(--text-muted)', cursor: 'pointer' }}>✕</span>
              </div>
            </>
          );
        })()}
        <br />
        This action will begin immediately and cannot be paused once started.
      </Modal>
      {pendingGenerate && (
        <div style={{ position: 'fixed', top: 24, right: 24, zIndex: 999, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, padding: '16px 24px', boxShadow: 'var(--shadow)' }}>
          <span role="img" aria-label="bolt">⚡</span> Generating scripts...
        </div>
      )}
    </>
  );
};

export default ScriptGeneratorPage;
